# Generated by Django 4.0.4 on 2022-05-31 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0003_category_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
