# Generated by Django 4.0.4 on 2022-06-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0005_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click me and see whats in me(blog post) !....', max_length=500),
        ),
    ]
