# Generated by Django 4.0.4 on 2022-06-02 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0008_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='titbiole',
            new_name='bio',
        ),
    ]
